title: Redacted Bundle
filename: RedactedBundle
filenameIdentifier: /case_details/id
coverpageTemplate: FL-FRM-APP-ENG-00002.docx
hasTableOfContents: true
hasCoversheets: true
customDocument: true
hasFolderCoversheets: false
pageNumberFormat: NUMBER_OF_PAGES
documentNameValue: /documentFileName
folders:
  - name: DWP
    documents:
      - type: documentSet
        property: /dwpDocuments