title: New bundle
filename: bundle.pdf
hasCoversheets: true
hasTableOfContents: true
documents:
  - type: documentSet
    property: /caseDocuments
    filters:
      - property: /name
        value: Document 1
