title: SSCS Bundle
filename: SscsBundle
filenameIdentifier: /case_details/id
coverpageTemplate: SSCS-cover-page.docx
hasTableOfContents: true
hasCoversheets: true
sort:
  field: /documentDateAdded
  order: ascending
hasFolderCoversheets: true
pageNumberFormat: numberOfPages
documentNameValue: /documentFileName
folders:
  - name: DWP
    documents:
      - type: documentSet
        property: /dwpDocuments
        filters:
          - property: /documentType
            value: dwpResponse
      - type: documentSet
        property: /dwpDocuments
        filters:
          - property: /documentType
            value: dwpEvidenceBundle
  - name: Original Documents
    documents:
      - type: documentSet
        property: /sscsDocument
        filters:
          - property: /bundleAddition
            value: \w+
  - name: Audio/video evidence
    documents:
      - type: document
        property: /audioVideoEvidenceBundleDocument
      - type: documentSet
        property: /sscsDocument
        filters:
          - property: /documentType
            value: rip1
  - name: Translated Documents
    documents:
      - type: documentSet
        property: /sscsWelshDocuments
        filters:
          - property: /bundleAddition
            value: \w+
      - type: documentSet
        property: /sscsWelshDocuments
        filters:
          - property: /documentType
            value: rip1
